version: '2'

services:
  matterhorn:
    build: 
      context: ./matterhorn
      args:
        - MATTERHORN_VER
        - MATTERHORN_BRANCH
    volumes:
      - /masterfiles:/masterfiles
      - /Library/WowzaStreamingEngine-4.1.2/avalon:/streamfiles
      - /private/tmp/matterhorn_work:/work
    ports:
      - "8080:8080"
